syntax = "proto3";

package hh.contracts.submits.v1;

service SubmitsService {
  rpc SubmitSolution(SubmitSolutionRequest) returns (SubmitSolutionResponse);
  rpc GetSubmission(GetSubmissionRequest) returns (GetSubmissionResponse);
}

message SubmitSolutionRequest {
  string team_id = 1;
  string hackathon_id = 2;
  string summary = 3;
  RepositoryBinding repository_binding = 4;
}

message SubmitSolutionResponse {
  Submission submission = 1;
}

message GetSubmissionRequest {
  string submission_id = 1;
}

message GetSubmissionResponse {
  Submission submission = 1;
}

message Submission {
  string id = 1;
  string team_id = 2;
  string hackathon_id = 3;
  string summary = 4;
  RepositoryBinding repository_binding = 5;
  int64 created_at = 6;
  repeated VerificationStatus verification_statuses = 7;
  int64 submission_deadline = 8;
}

message RepositoryBinding {
  string provider = 1;
  string repository = 2;
  string commit = 3;
  bool is_private = 4;
}

message VerificationStatus {
  string check = 1;
  string status = 2;
  string details = 3;
  int64 checked_at = 4;
}
