syntax = "proto3";

package hh.contracts.submits.v1;

service SubmitsService {
  rpc SubmitSolution(SubmitSolutionRequest) returns (SubmitSolutionResponse);
  rpc GetSubmission(GetSubmissionRequest) returns (GetSubmissionResponse);
}

message SubmitSolutionRequest {
  string participant_id = 1;
  string event_id = 2;
  string solution = 3;
}

message SubmitSolutionResponse {
  Submission submission = 1;
}

message GetSubmissionRequest {
  string submission_id = 1;
}

message GetSubmissionResponse {
  Submission submission = 1;
}

message Submission {
  string id = 1;
  string participant_id = 2;
  string event_id = 3;
  int64 submitted_at = 4;
  string status = 5;
}
